export const champsPrisEnCharge = [
  {
    type: 'text',
    icon: 'fa-font',
    label: 'Text',
    description: 'Enter your name',
    placeholder: 'Enter your name',
    className: 'form-control',
    subtype: 'text',
    regex: '',
    conditionVisibilite: '',
    handle: true,
  },
  {
    type: 'email',
    icon: 'fa-envelope',
    required: true,
    label: 'Email',
    description: 'Enter your email',
    placeholder: 'Enter your email',
    className: 'form-control',
    subtype: 'text',
    regex: '^([a-zA-Z0-9_.-]+)@([a-zA-Z0-9_.-]+).([a-zA-Z]{2,5})$',
    errorText: 'Please enter a valid email',
    conditionVisibilite: '',
    handle: true,
  },
  {
    type: 'phone',
    icon: 'fa-phone',
    label: 'Phone',
    description: 'Enter your phone',
    placeholder: 'Enter your phone',
    className: 'form-control',
    subtype: 'text',
    regex: '^[+]?[(]?[0-9]{3}[)]?[-s.]?[0-9]{3}[-s.]?[0-9]{4,6}$',
    errorText: 'Please enter a valid phone number',
    conditionVisibilite: '',
    handle: true,
  },
  {
    type: 'number',
    label: 'Number',
    icon: 'fa-html5',
    description: 'Age',
    placeholder: 'Enter your age',
    className: 'form-control',
    value: '20',
    min: 12,
    max: 90,
    conditionVisibilite: '',
  },
  {
    type: 'date',
    icon: 'fa-calendar',
    label: 'Date',
    placeholder: 'Date',
    className: 'form-control',
    conditionVisibilite: '',
  },
  {
    type: 'datetime-local',
    icon: 'fa-calendar',
    label: 'DateTime',
    placeholder: 'Date Time',
    className: 'form-control',
    conditionVisibilite: '',
  },
  {
    type: 'textarea',
    icon: 'fa-text-width',
    label: 'Textarea',
    conditionVisibilite: '',
  },
  {
    type: 'paragraph',
    icon: 'fa-paragraph',
    label: 'Paragraph',
    placeholder: 'Type your text to display here only',
    conditionVisibilite: '',
  },
  {
    type: 'checkbox',
    required: true,
    label: 'Checkbox',
    icon: 'fa-list',
    description: 'Checkbox',
    inline: true,
    conditionVisibilite: '',
    values: [
      {
        label: 'Option 1',
        value: 'option-1',
      },
      {
        label: 'Option 2',
        value: 'option-2',
      },
    ],
  },
  {
    type: 'radio',
    icon: 'fa-list-ul',
    label: 'Radio',
    description: 'Radio boxes',
    conditionVisibilite: '',
    values: [
      {
        label: 'Option 1',
        value: 'option-1',
      },
      {
        label: 'Option 2',
        value: 'option-2',
      },
    ],
  },
  {
    type: 'autocomplete',
    icon: 'fa-bars',
    label: 'Select',
    description: 'Select',
    placeholder: 'Select',
    className: 'form-control',
    conditionVisibilite: '',
    values: [
      {
        label: 'Option 1',
        value: 'option-1',
      },
      {
        label: 'Option 2',
        value: 'option-2',
      },
      {
        label: 'Option 3',
        value: 'option-3',
      },
    ],
  },
  {
    type: 'file',
    icon: 'fa-file',
    label: 'File Upload',
    className: 'form-control',
    subtype: 'file',
    conditionVisibilite: '',
  },
  {
    type: 'button',
    icon: 'fa-paper-plane',
    subtype: 'submit',
    label: 'Submit',
    conditionVisibilite: '',
  },
];
